import {NextUIProvider} from "@nextui-org/react";
// import localFont from "next/font/local";
import { Roboto, Anton } from 'next/font/google';
import "./globals.css";
import NavComponent from "@/components/nav/header";
import AuthProvider from "@/providers/authProvider";

const roboto = Roboto({
  weight:['400','700'],
  style:['normal','italic'],
  subsets:['latin'],
  display:'swap',
  variable:'--font-roboto'
});

const anton = Anton({
  weight:['400'],
  subsets:['latin'],
  display:'swap',
  variable:'--font-anton'
})



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${anton.variable} antialiased`}
      >
      <AuthProvider>
        <NextUIProvider>
          <NavComponent/>
          <>
            {children}
          </>
        </NextUIProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
